### ISSUE TITLE
No shadows/effect on Android visible

### ISSUE THREAD

**Issue by benjamin-carl** [calebnance/expo-neumorphism#3]
Hi @calebnance and thanks for providing this project to the public.

I've tried to get it working with shadows on my Android device and the online emulator as well. 
Do you know about this limitation (or bug)?

Can you please provide some more information on why the code does not work on Android?

Thanks in advance
best regards
Ben

**Comment by calebnance** [comment]
Hey @benjamin-carl, i don't think drop shadows are supported on android (rn out of the box). you can use [elevation](https://reactnative.dev/docs/view-style-props#elevation) but it's not as customizable so definitely not a 1:1 (also be aware of the zIndex it throws on the elements). i am sure there are some 3rd party libs out there, but i have not used any of them to achieve this on android. cheers!
